Javascript javascript1 week2
KristinaGru/hyf-homework pull request #5
Opened 2023-03-09 10:31 UTC by KristinaGru

2023-03-09 13:04 UTC, YurijPaharev requested changes
It is a magnificent and brilliant code! Still there is some place for improvement, please go through my comments

2023-03-09 13:04 UTC, YurijPaharev commented on javascript/javascript1/week2/full_name.js
> +    surname === '' ||
what if we pass just spaces? (like "      ")

2023-03-09 13:04 UTC, YurijPaharev commented on javascript/javascript1/week2/candy_helper.js
> +  }
You can use ternary here

2023-03-09 13:04 UTC, YurijPaharev commented on javascript/javascript1/week2/candy_helper.js
> +amountToSpend = Math.round(amountToSpend * 100) / 100;
You do not need to reassign this variable, you can do it in one line

2023-03-09 13:04 UTC, YurijPaharev commented on javascript/javascript1/week2/candy_helper.js
> +};
Nice using window.onload, but I think that you might want to use it wrapping all the DOM manipulations

2023-03-09 16:49 UTC, KristinaGru commented
> It is a magnificent and brilliant code! Still there is some place for improvement, please go through my comments

Thanks so much for all the feedback! I'll get right to it 🙌

2023-03-10 09:44 UTC, YurijPaharev approved these changes
It is great how far you are proceeding, I wouldn't do it better myself.
One thing though in the getFullName function you are using a long check `firstName === '' || typeof firstName !== 'string' || !firstName.trim()`. You can shorten it by just writing `typeof firstName !== 'string' || !firstName.trim()`. Because in this way you are checking that this value is indeed a string and after you are checking whether it has value or not, because string with spaces is converted to true, after we use trim() - it is converted to just empty string and `!''` is also converted to true. I encourage you to try it out and see results by yourself

2023-03-10 11:45 UTC, KristinaGru commented
> It is great how far you are proceeding, I wouldn't do it better myself. One thing though in the getFullName function you are using a long check `firstName === '' || typeof firstName !== 'string' || !firstName.trim()`. You can shorten it by just writing `typeof firstName !== 'string' || !firstName.trim()`. Because in this way you are checking that this value is indeed a string and after you are checking whether it has value or not, because string with spaces is converted to true, after we use trim() - it is converted to just empty string and `!''` is also converted to true. I encourage you to try it out and see results by yourself

I can definitely see the logic there! Thanks for all the notes and the encouragement, I really appreciate it

2023-03-10 11:46 UTC, merged